name: Node.js CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: 'Build latest docs and release'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build documentation
      run: ./run.sh
      env:
        CI: true
    - name: Push Changes
      run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git add docs
           git commit -m "prepare for release  ${{ github.ref }}"
           git push
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - build date  ${{ github.ref }}
          - based on 
          - * https://runtime.fivem.net/doc/natives_cfx.json
          - * https://runtime.fivem.net/doc/natives.json
        draft: false
        prerelease: false 
